apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appBaseName }}
  namespace: argocd
  labels:
    name: {{ .Values.appBaseName }}
spec:
  project: {{ .Values.project }}
  sources:
    - repoURL: {{ .Values.appRepo | quote }}
      targetRevision: {{ .Values.appBaseVersion | quote }}
      chart: {{ .Values.appBaseChart | quote }}
      helm:
        valueFiles:
        {{- range .Values.appValueFiles }}
          - $values/{{ $.Values.appBasePath }}/{{ . }}
        {{- end }}
        releaseName: {{ .Values.appBaseName | quote }}
    - repoURL: {{ .Values.backendRepo | quote }}
      targetRevision: master
      ref: values
  destination:
    server: {{ .Values.destination_server | quote }}
    namespace: {{ .Values.appNamespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
