{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginxconf
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  nginx.conf: {{ tpl .Values.configs.nginx.nginxconf $ | toYaml | indent 2 }}
{{- end }}
